name: GitHub Release

on:
  push:
    tags:
      - v*

jobs:
  create-github-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Calculate release name
        run: |
          GITHUB_REF=${{ github.ref }}
          RELEASE_NAME=${GITHUB_REF#"refs/tags/"}
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV
      - name: Publish release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
  publish-npm-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Clone npm
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3
        with:
          repository: npm/cli
          ref: provenance
          path: npm
      - name: Link npm
        run: |
          cd npm
          node . link
          cd ..
          npm version
      - run: npm ci
      - run: make build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_WEBAUTHN_JSON_PUBLISH_TOKEN }}
